import type { Metadata } from "next";
import { PLANS, PLAN_ORDER } from "@/lib/plans";
import { SECURITY_EMAIL, SUPPORT_EMAIL, absoluteUrl } from "./site";

export function pageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
  ogImage = "root",
  article,
}: {
  title: string;
  description: string;
  path: string;
  /** Use the title as-is instead of the "%s · Folevi" template. */
  absoluteTitle?: boolean;
  /**
   * "root": the site-wide image (src/app/opengraph-image.tsx). "segment": the page's own route segment has an
   * opengraph-image.tsx, so no image is listed here (a listed image would replace the file-based one).
   */
  ogImage?: "root" | "segment";
  /** Docs articles: shared as articles, with their last update (YYYY-MM-DD). */
  article?: { modified: string };
}): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = absoluteTitle ? title : `${title} · Folevi`;
  // Generated by src/app/opengraph-image.tsx. Listed explicitly because a page-level openGraph object
  // replaces the inherited file-based image.
  const image = { url: absoluteUrl("/opengraph-image"), width: 1200, height: 630, alt: "Folevi: a quieter place for ideas that keep growing." };
  const root = ogImage === "root";
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      ...(article ? { type: "article" as const, modifiedTime: article.modified } : { type: "website" as const }),
      url,
      siteName: "Folevi",
      title: fullTitle,
      description,
      locale: "en_US",
      ...(root ? { images: [image] } : {}),
    },
    // Without images here, Next copies the Open Graph image (the segment's file-based one) to Twitter.
    twitter: { card: "summary_large_image", title: fullTitle, description, ...(root ? { images: [image.url] } : {}) },
  };
}

/** Structured data. JSON is escaped so it can never close the script element. */
export function JsonLd({ data }: { data: Record<string, unknown> | Record<string, unknown>[] }) {
  const json = JSON.stringify(data).replace(/</g, "\\u003c");
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: json }} />;
}

export function organizationLd(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Folevi",
    url: absoluteUrl("/"),
    logo: absoluteUrl("/icon.svg"),
    email: SUPPORT_EMAIL,
    contactPoint: [
      { "@type": "ContactPoint", contactType: "customer support", email: SUPPORT_EMAIL, url: absoluteUrl("/support"), availableLanguage: "English" },
      { "@type": "ContactPoint", contactType: "security", email: SECURITY_EMAIL, url: absoluteUrl("/security") },
    ],
  };
}

/** The publisher block that articles point to. */
function publisher(): Record<string, unknown> {
  return { "@type": "Organization", name: "Folevi", url: absoluteUrl("/"), logo: { "@type": "ImageObject", url: absoluteUrl("/icon.svg") } };
}

export type Crumb = { name: string; path: string };

/** BreadcrumbList for a nested page. The first crumb is Home, the last is the page itself. */
export function breadcrumbLd(items: Crumb[]): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({ "@type": "ListItem", position: i + 1, name: item.name, item: absoluteUrl(item.path) })),
  };
}

export type FaqItem = { q: string; a: string };

/** FAQPage for a page that shows these questions and answers (answers are plain sentences). */
export function faqLd(path: string, faqs: FaqItem[]): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    url: absoluteUrl(path),
    mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
  };
}

/** Article, TechArticle or BlogPosting (docs, changelog entries, blog posts). Dates are YYYY-MM-DD. */
export function articleLd({
  type = "TechArticle",
  headline,
  description,
  path,
  published,
  modified,
  image,
  authorName,
  keywords,
}: {
  type?: "Article" | "TechArticle" | "BlogPosting";
  headline: string;
  description: string;
  path: string;
  published: string;
  modified?: string;
  /** Path of the article's Open Graph image. */
  image?: string;
  /** A byline other than the company (still an organization, e.g. "The Folevi team"). */
  authorName?: string;
  keywords?: string[];
}): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": type,
    headline,
    description,
    url: absoluteUrl(path),
    mainEntityOfPage: absoluteUrl(path),
    datePublished: published,
    dateModified: modified ?? published,
    inLanguage: "en",
    ...(image ? { image: absoluteUrl(image) } : {}),
    ...(keywords?.length ? { keywords: keywords.join(", ") } : {}),
    author: authorName ? { "@type": "Organization", name: authorName, url: absoluteUrl("/") } : publisher(),
    publisher: publisher(),
  };
}

export function softwareLd(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Folevi",
    url: absoluteUrl("/"),
    applicationCategory: "ProductivityApplication",
    operatingSystem: "Web",
    description:
      "A calm writing and notes workspace with block documents, nested pages, tasks, offline editing and real-time sync. It runs on the web, and a native Mac app is coming soon.",
    // The Personal plans, one offer per price, from the plan catalog (team plans cost the same per member).
    offers: PLAN_ORDER.flatMap((tier) => {
      const plan = PLANS[tier];
      if (tier === "free") return [{ "@type": "Offer", name: plan.name, price: 0, priceCurrency: "USD" }];
      return (["month", "year"] as const).map((interval) => {
        const price = (interval === "month" ? plan.monthlyCents : plan.yearlyCents) / 100;
        return {
          "@type": "Offer",
          name: `${plan.name} (${interval === "month" ? "monthly" : "yearly"})`,
          price,
          priceCurrency: "USD",
          priceSpecification: { "@type": "UnitPriceSpecification", price, priceCurrency: "USD", billingDuration: interval === "month" ? "P1M" : "P1Y" },
        };
      });
    }),
  };
}
