import type { Metadata } from "next";
import { absoluteUrl } from "./site";

export function pageMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Use the title as-is instead of the "%s · Folevi" template. */
  absoluteTitle?: boolean;
}): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = absoluteTitle ? title : `${title} · Folevi`;
  // Generated by src/app/opengraph-image.tsx. Listed explicitly because a page-level openGraph object
  // replaces the inherited file-based image.
  const image = { url: absoluteUrl("/opengraph-image"), width: 1200, height: 630, alt: "Folevi — A quieter place for ideas that keep growing." };
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      url,
      siteName: "Folevi",
      title: fullTitle,
      description,
      locale: "en_US",
      images: [image],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [image.url] },
  };
}

/** Structured data. JSON is escaped so it can never close the script element. */
export function JsonLd({ data }: { data: Record<string, unknown> | Record<string, unknown>[] }) {
  const json = JSON.stringify(data).replace(/</g, "\\u003c");
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: json }} />;
}

export function organizationLd(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Folevi",
    url: absoluteUrl("/"),
    logo: absoluteUrl("/icon.svg"),
    email: "security@folevi.com",
  };
}

export function softwareLd(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Folevi",
    url: absoluteUrl("/"),
    applicationCategory: "ProductivityApplication",
    operatingSystem: "Web",
    description:
      "A calm writing and notes workspace with block documents, nested pages, tasks, offline editing and real-time sync — on the web, with a native Mac app coming soon.",
    offers: [
      { "@type": "Offer", name: "Free", price: 0, priceCurrency: "USD" },
      { "@type": "Offer", name: "Basic", price: 2, priceCurrency: "USD", description: "Per month, or $9 a year" },
      { "@type": "Offer", name: "Pro", price: 5, priceCurrency: "USD", description: "Per month, or $49 a year" },
    ],
  };
}
