// Typed Convex API (generated by `convex dev` in /convex/_generated).
export { api, internal } from "../../../../../convex/_generated/api";
export type { Id, Doc } from "../../../../../convex/_generated/dataModel";
