#!/usr/bin/env node
// Generates CSS custom properties, a TypeScript module, and Swift tokens from src/tokens.json.
// `--check` fails when generated files are stale (used in CI).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repo = resolve(root, "../..");
const tokens = JSON.parse(readFileSync(resolve(root, "src/tokens.json"), "utf8"));
const check = process.argv.includes("--check");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/\./g, "_").toLowerCase();
const HEADER = "Generated by packages/design-tokens/scripts/build.mjs — do not edit.";

function cssVars(obj, prefix, unit = "") {
  return Object.entries(obj).map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v}${typeof v === "number" ? unit : ""};`);
}

function buildCss() {
  const { color, space, radius, font, layout, motion } = tokens;
  const light = cssVars(color.light, "color").join("\n");
  const dark = cssVars(color.dark, "color").join("\n");
  const shared = [
    ...cssVars(space, "space", "px"),
    ...cssVars(radius, "radius", "px"),
    ...cssVars(font.size, "text", "px"),
    ...Object.entries(font.lineHeight).map(([k, v]) => `  --leading-${kebab(k)}: ${v};`),
    ...Object.entries(font.weight).map(([k, v]) => `  --weight-${kebab(k)}: ${v};`),
    ...cssVars(layout, "layout", "px"),
    ...Object.entries(motion).map(([k, v]) => `  --motion-${kebab(k)}: ${typeof v === "number" ? `${v}ms` : v};`),
  ].join("\n");
  return `/* ${HEADER} */
:root {
${shared}
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replace(/^ {2}/gm, "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-base: 0ms;
    --motion-slow: 0ms;
    --motion-page: 0ms;
  }
}
`;
}

function buildTs() {
  return `// ${HEADER}
export const tokens = ${JSON.stringify({ ...tokens, $description: undefined, contrastPairs: undefined }, null, 2)} as const;

export type ColorToken = keyof typeof tokens.color.light;
export const documentAccents = ["accent", "moss", "marigold", "plum", "coral"] as const;
export type DocumentAccent = (typeof documentAccents)[number];
`;
}

function hexToRgb(hex) {
  const m = hex.match(/^#([0-9a-f]{6})$/i);
  if (m) {
    const n = parseInt(m[1], 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1];
  }
  const r = hex.match(/rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)/);
  if (r) return [Number(r[1]), Number(r[2]), Number(r[3]), Number(r[4])];
  throw new Error(`Unsupported color ${hex}`);
}

function buildSwift() {
  const names = Object.keys(tokens.color.light);
  const fmt = (n) => (n / 255).toFixed(4);
  const colorLines = names
    .map((name) => {
      const [lr, lg, lb, la] = hexToRgb(tokens.color.light[name]);
      const [dr, dg, db, da] = hexToRgb(tokens.color.dark[name]);
      return `    static let ${name} = Color(nsColor: .folevi(
        light: (${fmt(lr)}, ${fmt(lg)}, ${fmt(lb)}, ${la}),
        dark: (${fmt(dr)}, ${fmt(dg)}, ${fmt(db)}, ${da}),
        name: "folevi.${name}"
    ))`;
    })
    .join("\n");
  const num = (obj) =>
    Object.entries(obj)
      .map(([k, v]) => `    static let ${/^\d/.test(k) ? `s${k.replace(".", "_")}` : k}: CGFloat = ${v}`)
      .join("\n");
  return `// ${HEADER}
import AppKit
import SwiftUI

extension NSColor {
    /// A dynamic color that resolves against the current appearance, including increased-contrast variants.
    static func folevi(
        light: (CGFloat, CGFloat, CGFloat, CGFloat),
        dark: (CGFloat, CGFloat, CGFloat, CGFloat),
        name: String
    ) -> NSColor {
        NSColor(name: NSColor.Name(name)) { appearance in
            let isDark = appearance.bestMatch(from: [.darkAqua, .vibrantDark, .accessibilityHighContrastDarkAqua]) != nil
            let c = isDark ? dark : light
            return NSColor(srgbRed: c.0, green: c.1, blue: c.2, alpha: c.3)
        }
    }
}

enum FoleviColor {
${colorLines}
}

enum FoleviSpace {
${num(tokens.space)}
}

enum FoleviRadius {
${num(tokens.radius)}
}

enum FoleviLayout {
${num(tokens.layout)}
}

enum FoleviMotion {
    static let fast: Double = ${tokens.motion.fast / 1000}
    static let base: Double = ${tokens.motion.base / 1000}
    static let slow: Double = ${tokens.motion.slow / 1000}
    static let page: Double = ${tokens.motion.page / 1000}
}
`;
}

const outputs = [
  [resolve(root, "generated/tokens.css"), buildCss()],
  [resolve(root, "generated/tokens.ts"), buildTs()],
  [resolve(repo, "apps/macos/Folevi/DesignSystem/Generated/FoleviTokens.swift"), buildSwift()],
];

let stale = false;
for (const [file, content] of outputs) {
  if (check) {
    if (!existsSync(file) || readFileSync(file, "utf8") !== content) {
      console.error(`stale: ${file}`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${file.replace(repo + "/", "")}`);
}
if (stale) {
  console.error("Design tokens are stale. Run `pnpm tokens`.");
  process.exit(1);
}
