#!/usr/bin/env node
// Generates CSS custom properties, a TypeScript module, and Swift tokens from src/tokens.json.
// `--check` fails when generated files are stale (used in CI).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repo = resolve(root, "../..");
const tokens = JSON.parse(readFileSync(resolve(root, "src/tokens.json"), "utf8"));
const check = process.argv.includes("--check");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/\./g, "_").toLowerCase();
const HEADER = "Generated by packages/design-tokens/scripts/build.mjs — do not edit.";

const stripMeta = (obj) => Object.fromEntries(Object.entries(obj).filter(([k]) => !k.startsWith("$")));

function cssVars(obj, prefix, unit = "") {
  return Object.entries(obj).map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v}${typeof v === "number" ? unit : ""};`);
}

const shadowCss = (layers) =>
  layers.map(([x, y, blur, spread, c, inset]) => `${inset ? "inset " : ""}${x}px ${y}px ${blur}px ${spread}px ${c}`).join(", ");
const shadowVars = (theme) => Object.entries(tokens.shadow[theme]).map(([k, v]) => `  --shadow-${kebab(k)}: ${shadowCss(v)};`);

function buildCss() {
  const { color, space, radius, font, layout, motion } = tokens;
  const light = [...cssVars(color.light, "color"), ...shadowVars("light")].join("\n");
  const dark = [...cssVars(color.dark, "color"), ...shadowVars("dark")].join("\n");
  const shared = [
    ...cssVars(space, "space", "px"),
    ...cssVars(radius, "radius", "px"),
    ...cssVars(font.size, "text", "px"),
    ...Object.entries(font.lineHeight).map(([k, v]) => `  --leading-${kebab(k)}: ${v};`),
    ...Object.entries(font.weight).map(([k, v]) => `  --weight-${kebab(k)}: ${v};`),
    ...Object.entries(font.tracking).map(([k, v]) => `  --tracking-${kebab(k)}: ${v}em;`),
    ...Object.entries(font.family).map(([k, v]) => `  --font-family-${kebab(k)}: "${v}";`),
    ...cssVars(layout, "layout", "px"),
    ...Object.entries(motion).map(([k, v]) => `  --motion-${kebab(k)}: ${typeof v === "number" ? `${v}ms` : v};`),
  ].join("\n");
  const chromeLight = cssVars(stripMeta(tokens.chrome.light), "color").join("\n");
  const chromeDark = cssVars(stripMeta(tokens.chrome.dark), "color").join("\n");
  const glassLight = cssVars(stripMeta(tokens.glass.light), "glass").join("\n");
  const glassDark = cssVars(stripMeta(tokens.glass.dark), "glass").join("\n");
  return `/* ${HEADER} */
:root {
${shared}
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replace(/^ {2}/gm, "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}

/* Neutral app chrome (tokens.chrome): inside the product; AccountGate sets data-chrome="neutral". */
:root[data-chrome="neutral"] {
${chromeLight}
}

:root[data-chrome="neutral"][data-theme="dark"] {
${chromeDark}
}

/* Glass (tokens.glass). */
:root {
${glassLight}
}

:root[data-theme="dark"] {
${glassDark}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-base: 0ms;
    --motion-slow: 0ms;
    --motion-page: 0ms;
  }
}
`;
}

function buildTs() {
  return `// ${HEADER}
export const tokens = ${JSON.stringify({ ...tokens, $description: undefined, contrastPairs: undefined }, null, 2)} as const;

export type ColorToken = keyof typeof tokens.color.light;
export const documentAccents = ["accent", "moss", "marigold", "plum", "coral"] as const;
export type DocumentAccent = (typeof documentAccents)[number];
`;
}

function hexToRgb(hex) {
  const m = hex.match(/^#([0-9a-f]{6})$/i);
  if (m) {
    const n = parseInt(m[1], 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1];
  }
  const r = hex.match(/rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)/);
  if (r) return [Number(r[1]), Number(r[2]), Number(r[3]), Number(r[4])];
  throw new Error(`Unsupported color ${hex}`);
}

function shadowLines() {
  const fmt = (n) => (n / 255).toFixed(4);
  const names = Object.keys(tokens.shadow.light);
  return names
    .map((name) => {
      const light = tokens.shadow.light[name];
      const dark = tokens.shadow.dark[name];
      const n = Math.max(light.length, dark.length);
      const layers = [];
      // Layers pair up by index; a theme with fewer layers uses a transparent layer.
      for (let i = 0; i < n; i++) {
        const l = light[i] ?? [0, 0, 0, 0, "rgba(0, 0, 0, 0)"];
        const d = dark[i] ?? [0, 0, 0, 0, "rgba(0, 0, 0, 0)"];
        const [lr, lg, lb, la] = hexToRgb(l[4]);
        const [dr, dg, db, da] = hexToRgb(d[4]);
        layers.push(`        FoleviShadowLayer(x: ${l[0]}, y: ${l[1]}, blur: ${l[2]}, spread: ${l[3]}, color: Color(nsColor: .folevi(
            light: (${fmt(lr)}, ${fmt(lg)}, ${fmt(lb)}, ${la}),
            dark: (${fmt(dr)}, ${fmt(dg)}, ${fmt(db)}, ${da}),
            name: "folevi.shadow.${name}.${i}"
        )), inset: ${Boolean(l[5] || d[5])}),`);
      }
      return `    static let ${name}: [FoleviShadowLayer] = [\n${layers.join("\n")}\n    ]`;
    })
    .join("\n");
}

function buildSwift() {
  const fmt = (n) => (n / 255).toFixed(4);
  const dynamicColors = (light, dark, prefix) =>
    Object.keys(light)
      .map((name) => {
        const [lr, lg, lb, la] = hexToRgb(light[name]);
        const [dr, dg, db, da] = hexToRgb(dark[name]);
        return `    static let ${name} = Color(nsColor: .folevi(
        light: (${fmt(lr)}, ${fmt(lg)}, ${fmt(lb)}, ${la}),
        dark: (${fmt(dr)}, ${fmt(dg)}, ${fmt(db)}, ${da}),
        name: "${prefix}.${name}"
    ))`;
      })
      .join("\n");
  // The Mac app is all product, so the neutral chrome replaces the marketing palette where it differs.
  const colorLines = dynamicColors(
    { ...tokens.color.light, ...stripMeta(tokens.chrome.light) },
    { ...tokens.color.dark, ...stripMeta(tokens.chrome.dark) },
    "folevi",
  );
  const glassLines = dynamicColors(stripMeta(tokens.glass.light), stripMeta(tokens.glass.dark), "folevi.glass");
  const num = (obj) =>
    Object.entries(obj)
      .map(([k, v]) => `    static let ${/^\d/.test(k) ? `s${k.replace(".", "_")}` : k}: CGFloat = ${v}`)
      .join("\n");
  return `// ${HEADER}
import AppKit
import SwiftUI

extension NSColor {
    /// A dynamic color that resolves against the current appearance, including increased-contrast variants.
    static func folevi(
        light: (CGFloat, CGFloat, CGFloat, CGFloat),
        dark: (CGFloat, CGFloat, CGFloat, CGFloat),
        name: String
    ) -> NSColor {
        NSColor(name: NSColor.Name(name)) { appearance in
            let isDark = appearance.bestMatch(from: [.darkAqua, .vibrantDark, .accessibilityHighContrastDarkAqua]) != nil
            let c = isDark ? dark : light
            return NSColor(srgbRed: c.0, green: c.1, blue: c.2, alpha: c.3)
        }
    }
}

/// Colors: \`tokens.color\` with the neutral product chrome (\`tokens.chrome\`) applied.
enum FoleviColor {
${colorLines}
}

/// Translucent glass layers (\`tokens.glass\`), as the web's --glass-* variables.
enum FoleviGlass {
${glassLines}
}

/// One layer of a token shadow. SwiftUI draws outer layers with \`.shadow\`; spread and inset
/// highlights are approximated by the components (inset → a 1pt top stroke).
struct FoleviShadowLayer {
    let x: CGFloat
    let y: CGFloat
    let blur: CGFloat
    let spread: CGFloat
    let color: Color
    let inset: Bool
}

enum FoleviShadow {
${shadowLines()}
}

enum FoleviFontFamily {
${Object.entries(tokens.font.family).map(([k, v]) => `    static let ${k} = "${v}"`).join("\n")}
}

enum FoleviFontSize {
${num(tokens.font.size)}
}

/// Letter spacing as a fraction of the font size (multiply by the point size for \`.tracking\`).
enum FoleviTracking {
${num(tokens.font.tracking)}
}

enum FoleviSpace {
${num(tokens.space)}
}

enum FoleviRadius {
${num(tokens.radius)}
}

enum FoleviLayout {
${num(tokens.layout)}
}

enum FoleviMotion {
    static let fast: Double = ${tokens.motion.fast / 1000}
    static let base: Double = ${tokens.motion.base / 1000}
    static let slow: Double = ${tokens.motion.slow / 1000}
    static let page: Double = ${tokens.motion.page / 1000}
}
`;
}

const outputs = [
  [resolve(root, "generated/tokens.css"), buildCss()],
  [resolve(root, "generated/tokens.ts"), buildTs()],
  [resolve(repo, "apps/macos/Folevi/DesignSystem/Generated/FoleviTokens.swift"), buildSwift()],
];

let stale = false;
for (const [file, content] of outputs) {
  if (check) {
    if (!existsSync(file) || readFileSync(file, "utf8") !== content) {
      console.error(`stale: ${file}`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${file.replace(repo + "/", "")}`);
}
if (stale) {
  console.error("Design tokens are stale. Run `pnpm tokens`.");
  process.exit(1);
}
