#!/usr/bin/env node
// Generates CSS custom properties and a TypeScript module from src/tokens.json.
// `--check` fails when generated files are stale (used in CI).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const repo = resolve(root, "../..");
const tokens = JSON.parse(readFileSync(resolve(root, "src/tokens.json"), "utf8"));
const check = process.argv.includes("--check");

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/\./g, "_").toLowerCase();
const HEADER = "Generated by packages/design-tokens/scripts/build.mjs. Do not edit.";

const stripMeta = (obj) => Object.fromEntries(Object.entries(obj).filter(([k]) => !k.startsWith("$")));

function cssVars(obj, prefix, unit = "") {
  return Object.entries(obj).map(([k, v]) => `  --${prefix}-${kebab(k)}: ${v}${typeof v === "number" ? unit : ""};`);
}

const shadowCss = (layers) =>
  layers.map(([x, y, blur, spread, c, inset]) => `${inset ? "inset " : ""}${x}px ${y}px ${blur}px ${spread}px ${c}`).join(", ");
const shadowVars = (theme) => Object.entries(tokens.shadow[theme]).map(([k, v]) => `  --shadow-${kebab(k)}: ${shadowCss(v)};`);

function buildCss() {
  const { color, space, radius, font, layout, motion } = tokens;
  const light = [...cssVars(color.light, "color"), ...shadowVars("light")].join("\n");
  const dark = [...cssVars(color.dark, "color"), ...shadowVars("dark")].join("\n");
  const shared = [
    ...cssVars(space, "space", "px"),
    ...cssVars(radius, "radius", "px"),
    ...cssVars(font.size, "text", "px"),
    ...Object.entries(font.lineHeight).map(([k, v]) => `  --leading-${kebab(k)}: ${v};`),
    ...Object.entries(font.weight).map(([k, v]) => `  --weight-${kebab(k)}: ${v};`),
    ...Object.entries(font.tracking).map(([k, v]) => `  --tracking-${kebab(k)}: ${v}em;`),
    ...Object.entries(font.family).map(([k, v]) => `  --font-family-${kebab(k)}: "${v}";`),
    ...cssVars(layout, "layout", "px"),
    ...Object.entries(motion).map(([k, v]) => `  --motion-${kebab(k)}: ${typeof v === "number" ? `${v}ms` : v};`),
  ].join("\n");
  const chromeLight = cssVars(stripMeta(tokens.chrome.light), "color").join("\n");
  const chromeDark = cssVars(stripMeta(tokens.chrome.dark), "color").join("\n");
  const glassLight = cssVars(stripMeta(tokens.glass.light), "glass").join("\n");
  const glassDark = cssVars(stripMeta(tokens.glass.dark), "glass").join("\n");
  return `/* ${HEADER} */
:root {
${shared}
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replace(/^ {2}/gm, "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}

/* Neutral app chrome (tokens.chrome): inside the product. AccountGate and the admin console set
   data-chrome="neutral"; server-rendered pages (sign in, shared notes) carry a .ui-neutral-chrome element. */
:root[data-chrome="neutral"],
:root:has(.ui-neutral-chrome) {
${chromeLight}
}

:root[data-chrome="neutral"][data-theme="dark"],
:root[data-theme="dark"]:has(.ui-neutral-chrome) {
${chromeDark}
}

/* Glass (tokens.glass). */
:root {
${glassLight}
}

:root[data-theme="dark"] {
${glassDark}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-base: 0ms;
    --motion-slow: 0ms;
    --motion-page: 0ms;
  }
}
`;
}

function buildTs() {
  return `// ${HEADER}
export const tokens = ${JSON.stringify({ ...tokens, $description: undefined, contrastPairs: undefined }, null, 2)} as const;

export type ColorToken = keyof typeof tokens.color.light;
export const documentAccents = ["accent", "moss", "marigold", "plum", "coral"] as const;
export type DocumentAccent = (typeof documentAccents)[number];
`;
}

const outputs = [
  [resolve(root, "generated/tokens.css"), buildCss()],
  [resolve(root, "generated/tokens.ts"), buildTs()],
];

let stale = false;
for (const [file, content] of outputs) {
  if (check) {
    if (!existsSync(file) || readFileSync(file, "utf8") !== content) {
      console.error(`stale: ${file}`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${file.replace(repo + "/", "")}`);
}
if (stale) {
  console.error("Design tokens are stale. Run `pnpm tokens`.");
  process.exit(1);
}
