// Source of truth for every transactional email Folevi sends through Loops.
//
// Each entry maps to exactly one *published* Loops transactional template whose
// id lives in the env var named by `envVar`. Templates are authored as MJML in
// `packages/email/templates/<key>.mjml` (generated by scripts/build-templates.ts)
// and imported into Loops by hand; see docs/EMAIL_OPERATIONS.md.
//
// Rules:
// - Identity/security templates are never unsubscribable and carry no marketing footer.
// - Product notifications honor Folevi-side preferences (`preferenceKey`) and always link
//   to `preferencesUrl`.
// - Variables are deliberately minimal: never note bodies, TOTP secrets, backup codes,
//   passwords or tokens beyond the single action link.
// - Subjects are static on purpose: user-controlled strings (names, titles) never appear
//   in a subject line, which limits spoofing/phishing via crafted display names.
//
// This file must only use `import type` so Node can load it with type stripping.

import type { TemplateDefinition, TemplateKey } from "./types";

const SECURITY_SENDER = { name: "Folevi", localPart: "security" } as const;
const PRODUCT_SENDER = { name: "Folevi", localPart: "hello" } as const;

const url = (description: string, required = true) =>
  ({ type: "string", required, format: "url", maxLength: 2048, description }) as const;
const text = (description: string, maxLength: number, required = true) =>
  ({ type: "string", required, format: "text", maxLength, description }) as const;
const num = (description: string) => ({ type: "number", required: true, description }) as const;

const FIX_APP = "https://app.folevi.com";
const FIX_AUTH = "https://auth.folevi.com";

const definitions: Record<TemplateKey, TemplateDefinition> = {
  auth_verify_email: {
    key: "auth_verify_email",
    category: "identity",
    envVar: "LOOPS_TRANSACTIONAL_AUTH_VERIFY_EMAIL_ID",
    subject: "Confirm your email for Folevi",
    previewText: "Confirm this address to finish setting up your Folevi account.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      actionUrl: url("Auth0 email-verification link (host-restricted by the Auth0 action)."),
      expiresInHours: num(
        "Hours until the link expires (matches the Auth0 template URL lifetime).",
      ),
    },
    fixture: {
      actionUrl: `${FIX_AUTH}/u/email-verification?ticket=EXAMPLEticket123#`,
      expiresInHours: 24,
    },
    source: { kind: "mjml", path: "templates/auth_verify_email.mjml" },
  },
  auth_password_reset: {
    key: "auth_password_reset",
    category: "identity",
    envVar: "LOOPS_TRANSACTIONAL_AUTH_PASSWORD_RESET_ID",
    subject: "Reset your Folevi password",
    previewText: "Use this link to choose a new password. If you did not ask, ignore this email.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      actionUrl: url("Auth0 password-reset link."),
      expiresInHours: num("Hours until the link expires."),
    },
    fixture: {
      actionUrl: `${FIX_AUTH}/u/reset-verify?ticket=EXAMPLEticket456#`,
      expiresInHours: 1,
    },
    source: { kind: "mjml", path: "templates/auth_password_reset.mjml" },
  },
  auth_blocked_account: {
    key: "auth_blocked_account",
    category: "identity",
    envVar: "LOOPS_TRANSACTIONAL_AUTH_BLOCKED_ACCOUNT_ID",
    subject: "Sign-in to your Folevi account was paused",
    previewText: "We paused sign-in after several failed attempts. You can unblock it here.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      actionUrl: url("Auth0 unblock link."),
      expiresInHours: num("Hours until the link expires."),
    },
    fixture: {
      actionUrl: `${FIX_AUTH}/lo/unblock?ticket=EXAMPLEticket789`,
      expiresInHours: 24,
    },
    source: { kind: "mjml", path: "templates/auth_blocked_account.mjml" },
  },
  auth_breached_password: {
    key: "auth_breached_password",
    category: "identity",
    envVar: "LOOPS_TRANSACTIONAL_AUTH_BREACHED_PASSWORD_ID",
    subject: "Your Folevi password appeared in a data breach",
    previewText: "Your password was found in a breach elsewhere. Please choose a new one.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      actionUrl: url("Auth0 password-change link included in the breached-password notice."),
      expiresInHours: num("Hours until the link expires."),
    },
    fixture: {
      actionUrl: `${FIX_AUTH}/u/reset-verify?ticket=EXAMPLEticket000#`,
      expiresInHours: 24,
    },
    source: { kind: "mjml", path: "templates/auth_breached_password.mjml" },
  },
  auth_verification_code: {
    key: "auth_verification_code",
    category: "identity",
    envVar: "LOOPS_TRANSACTIONAL_AUTH_VERIFICATION_CODE_ID",
    subject: "Your Folevi verification code",
    previewText: "Enter this one-time code to continue. It expires shortly.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      code: {
        type: "string",
        required: true,
        format: "code",
        maxLength: 12,
        description: "One-time code issued by Auth0 (verify/reset by code flows).",
      },
      expiresInMinutes: num("Minutes until the code expires."),
    },
    fixture: { code: "482913", expiresInMinutes: 10 },
    source: { kind: "mjml", path: "templates/auth_verification_code.mjml" },
  },
  security_new_device: {
    key: "security_new_device",
    category: "security",
    envVar: "LOOPS_TRANSACTIONAL_SECURITY_NEW_DEVICE_ID",
    subject: "New sign-in to your Folevi account",
    previewText: "A new device signed in to your account. Review it if this was not you.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      deviceLabel: text('Human label, e.g. "Safari on macOS".', 80),
      approximateLocation: text(
        'Coarse location (city/region). Optional: pass "Not available" rather than omitting when unknown.',
        80,
        false,
      ),
      signedInAt: text("Pre-formatted sign-in time including timezone.", 64),
      securityUrl: url("Link to Settings > Security (sessions & devices)."),
    },
    fixture: {
      deviceLabel: "Safari on macOS",
      approximateLocation: "Lisbon, Portugal",
      signedInAt: "25 September 2026, 10:42 UTC",
      securityUrl: `${FIX_APP}/settings/security`,
    },
    source: { kind: "mjml", path: "templates/security_new_device.mjml" },
  },
  account_deletion_scheduled: {
    key: "account_deletion_scheduled",
    category: "security",
    envVar: "LOOPS_TRANSACTIONAL_ACCOUNT_DELETION_SCHEDULED_ID",
    subject: "Your Folevi account is scheduled for deletion",
    previewText: "Your account and notes will be deleted. You can still cancel.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      scheduledFor: text("Pre-formatted deletion date.", 64),
      cancelUrl: url("Link to cancel the scheduled deletion (requires sign-in)."),
    },
    fixture: {
      scheduledFor: "9 October 2026",
      cancelUrl: `${FIX_APP}/settings/account/deletion`,
    },
    source: { kind: "mjml", path: "templates/account_deletion_scheduled.mjml" },
  },
  account_deletion_completed: {
    key: "account_deletion_completed",
    category: "security",
    envVar: "LOOPS_TRANSACTIONAL_ACCOUNT_DELETION_COMPLETED_ID",
    subject: "Your Folevi account has been deleted",
    previewText: "Your account and its data have been deleted.",
    sender: SECURITY_SENDER,
    unsubscribable: false,
    variables: {
      completedOn: text("Pre-formatted date the deletion completed.", 64),
    },
    fixture: { completedOn: "9 October 2026" },
    source: { kind: "mjml", path: "templates/account_deletion_completed.mjml" },
  },
  workspace_invite: {
    key: "workspace_invite",
    category: "product",
    envVar: "LOOPS_TRANSACTIONAL_WORKSPACE_INVITE_ID",
    subject: "You have been invited to a Folevi workspace",
    previewText: "Accept the invitation to start working together in Folevi.",
    sender: PRODUCT_SENDER,
    unsubscribable: true,
    preferenceKey: "invites",
    variables: {
      inviterName: text("Display name of the inviter (user-controlled).", 80),
      workspaceName: text("Workspace name (user-controlled).", 80),
      role: text('Role granted, e.g. "Editor".', 32),
      acceptUrl: url("Invitation acceptance link."),
      expiresInDays: num("Days until the invitation expires."),
      preferencesUrl: url("Email preferences page."),
    },
    fixture: {
      inviterName: "Maya Okafor",
      workspaceName: "Field Notes",
      role: "Editor",
      acceptUrl: `${FIX_APP}/invite/EXAMPLEinvite`,
      expiresInDays: 7,
      preferencesUrl: `${FIX_APP}/settings/notifications`,
    },
    source: { kind: "mjml", path: "templates/workspace_invite.mjml" },
  },
  mention_notification: {
    key: "mention_notification",
    category: "product",
    envVar: "LOOPS_TRANSACTIONAL_MENTION_NOTIFICATION_ID",
    subject: "You were mentioned in Folevi",
    previewText: "Someone mentioned you in a document.",
    sender: PRODUCT_SENDER,
    unsubscribable: true,
    preferenceKey: "mentions",
    variables: {
      actorName: text("Display name of the person who mentioned you.", 80),
      documentTitle: text("Document title (user-controlled).", 120),
      excerpt: text("Minimal preview around the mention (user-controlled).", 140, false),
      documentUrl: url("Deep link to the mention."),
      preferencesUrl: url("Email preferences page."),
    },
    fixture: {
      actorName: "Maya Okafor",
      documentTitle: "Spring planting plan",
      excerpt: "…could you check the soil notes before Friday?",
      documentUrl: `${FIX_APP}/d/EXAMPLEdoc#mention`,
      preferencesUrl: `${FIX_APP}/settings/notifications`,
    },
    source: { kind: "mjml", path: "templates/mention_notification.mjml" },
  },
  comment_notification: {
    key: "comment_notification",
    category: "product",
    envVar: "LOOPS_TRANSACTIONAL_COMMENT_NOTIFICATION_ID",
    subject: "New comment in Folevi",
    previewText: "Someone commented on a document you follow.",
    sender: PRODUCT_SENDER,
    unsubscribable: true,
    preferenceKey: "comments",
    variables: {
      actorName: text("Display name of the commenter.", 80),
      documentTitle: text("Document title (user-controlled).", 120),
      excerpt: text("Minimal preview of the comment (user-controlled).", 140, false),
      documentUrl: url("Deep link to the comment thread."),
      preferencesUrl: url("Email preferences page."),
    },
    fixture: {
      actorName: "Jonas Lindqvist",
      documentTitle: "Q4 reading list",
      excerpt: "Added two more titles to the shortlist.",
      documentUrl: `${FIX_APP}/d/EXAMPLEdoc#comment`,
      preferencesUrl: `${FIX_APP}/settings/notifications`,
    },
    source: { kind: "mjml", path: "templates/comment_notification.mjml" },
  },
  comment_digest: {
    key: "comment_digest",
    category: "product",
    envVar: "LOOPS_TRANSACTIONAL_COMMENT_DIGEST_ID",
    subject: "Your Folevi comment digest",
    previewText: "A summary of recent comments on your documents.",
    sender: PRODUCT_SENDER,
    unsubscribable: true,
    preferenceKey: "digest",
    variables: {
      count: num("Number of new comments summarised."),
      summary: text("Plain-text summary (titles and names only, no comment bodies).", 500),
      inboxUrl: url("Link to the in-app inbox."),
      preferencesUrl: url("Email preferences page."),
    },
    fixture: {
      count: 4,
      summary: "3 comments on Spring planting plan; 1 comment on Q4 reading list.",
      inboxUrl: `${FIX_APP}/inbox`,
      preferencesUrl: `${FIX_APP}/settings/notifications`,
    },
    source: { kind: "mjml", path: "templates/comment_digest.mjml" },
  },
  share_notification: {
    key: "share_notification",
    category: "product",
    envVar: "LOOPS_TRANSACTIONAL_SHARE_NOTIFICATION_ID",
    subject: "A document was shared with you in Folevi",
    previewText: "You now have access to a document in Folevi.",
    sender: PRODUCT_SENDER,
    unsubscribable: true,
    preferenceKey: "shares",
    variables: {
      actorName: text("Display name of the person who shared.", 80),
      documentTitle: text("Document title (user-controlled).", 120),
      role: text('Access level, e.g. "Can comment".', 32),
      documentUrl: url("Link to the document."),
      preferencesUrl: url("Email preferences page."),
    },
    fixture: {
      actorName: "Maya Okafor",
      documentTitle: "Spring planting plan",
      role: "Can edit",
      documentUrl: `${FIX_APP}/d/EXAMPLEdoc`,
      preferencesUrl: `${FIX_APP}/settings/notifications`,
    },
    source: { kind: "mjml", path: "templates/share_notification.mjml" },
  },
};

function deepFreeze<T>(value: T): T {
  if (value && typeof value === "object") {
    for (const v of Object.values(value)) deepFreeze(v);
    Object.freeze(value);
  }
  return value;
}

export const emailManifest: Readonly<Record<TemplateKey, TemplateDefinition>> =
  deepFreeze(definitions);

export const TEMPLATE_KEYS: readonly TemplateKey[] = Object.freeze(
  Object.keys(definitions) as TemplateKey[],
);

/**
 * Auth0 custom-email-provider `message_type` → Loops template.
 * `null` = intentionally dropped by the Auth0 action (see infra/auth0/actions/custom-email-provider.js,
 * which must carry the identical mapping; a test enforces this).
 * - welcome_email: Folevi does not send an Auth0 welcome email.
 * - mfa_oob_code / enrollment_email: email is not an MFA factor for Folevi (OTP only).
 * - verification_code / organization_invitation: passwordless and Organizations are disabled.
 * - try_provider_configuration_email: handled specially (configuration check, nothing sent).
 */
export const AUTH0_MESSAGE_TYPE_TO_TEMPLATE: Record<string, TemplateKey | null> = Object.freeze({
  verify_email: "auth_verify_email",
  verify_email_by_code: "auth_verification_code",
  reset_email: "auth_password_reset",
  reset_email_by_code: "auth_verification_code",
  blocked_account: "auth_blocked_account",
  stolen_credentials: "auth_breached_password",
  welcome_email: null,
  verification_code: null,
  mfa_oob_code: null,
  enrollment_email: null,
  organization_invitation: null,
  try_provider_configuration_email: null,
});
