import type { WireBlock } from "@folevi/editor-schema";
import { specsToWireBlocks, type BlockSpec } from "./create";
import { weeklyResetBlocks } from "./seedContent";

// Small builders so each template reads like the page it makes.
const h2 = (md: string): BlockSpec => ({ type: "heading", props: { level: 2 }, md });
const h3 = (md: string): BlockSpec => ({ type: "heading", props: { level: 3 }, md });
const p = (md = ""): BlockSpec => ({ type: "paragraph", md });
const b = (md = ""): BlockSpec => ({ type: "bulleted", md });
const n = (md = ""): BlockSpec => ({ type: "numbered", md });
const todo = (md = ""): BlockSpec => ({ type: "todo", props: { checked: false }, md });
const quote = (md = ""): BlockSpec => ({ type: "quote", md });
const callout = (tone: "note" | "info" | "success" | "warning" | "danger", md: string): BlockSpec => ({ type: "callout", props: { tone }, md });
const toggle = (md: string, children: BlockSpec[]): BlockSpec => ({ type: "toggle", props: { collapsed: false }, md, children });
const divider = (): BlockSpec => ({ type: "divider", props: {} });
/** A table with a header row and `rows` empty rows (or given first-column labels). */
function table(headers: string[], rows: number | string[] = 2): BlockSpec {
  const cell = (text: string) => (text ? [{ type: "text", text }] : []);
  const body = typeof rows === "number" ? Array.from({ length: rows }, () => headers.map(() => cell(""))) : rows.map((label) => headers.map((_, i) => cell(i === 0 ? label : "")));
  return { type: "table", props: { headerRow: true, rows: [headers.map(cell), ...body] } };
}

/**
 * Built-in, immutable starter templates. Admins can enable/disable them (builtInTemplates table).
 * `icon` is an outlined icon name the clients draw (web: components/ui/TemplateIcon.tsx) — never an emoji.
 */
export const BUILT_IN_TEMPLATES: { key: string; name: string; description: string; icon: string; blocks: () => BlockSpec[] }[] = [
  // ---- Everyday
  {
    key: "daily-page",
    name: "Daily Page",
    description: "A light structure for a day: intentions, notes and a short look back.",
    icon: "sun",
    blocks: () => [h3("Intentions"), todo(), h3("Notes"), p(), h3("Looking back"), p()],
  },
  {
    key: "weekly-reset",
    name: "Weekly Reset",
    description: "Close last week and open the next in thirty quiet minutes.",
    icon: "refresh-cw",
    blocks: weeklyResetBlocks,
  },
  {
    key: "monthly-review",
    name: "Monthly Review",
    description: "Wins, lessons and numbers from the month, and what to change next.",
    icon: "calendar-range",
    blocks: () => [
      callout("note", "**Month:** · **Energy (1–10):**"),
      h2("Highlights"),
      b(),
      h2("What I learned"),
      b(),
      h2("By the numbers"),
      table(["Measure", "Target", "Actual"], ["", ""]),
      h2("Next month"),
      n("Keep doing"),
      n("Start doing"),
      n("Stop doing"),
    ],
  },
  {
    key: "journal",
    name: "Journal Entry",
    description: "Gentle prompts for gratitude, how the day felt and what's on your mind.",
    icon: "heart",
    blocks: () => [
      h3("Three things I'm grateful for"),
      n(),
      n(),
      n(),
      h3("How today felt"),
      p(),
      h3("On my mind"),
      p(),
      divider(),
      quote("One line to remember today by."),
    ],
  },
  {
    key: "habit-tracker",
    name: "Habit Tracker",
    description: "A week-at-a-glance grid for the habits you're building.",
    icon: "calendar-check",
    blocks: () => [
      p("Tick a day when you did it. Aim for streaks, not perfection."),
      table(["Habit", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], ["Move for 30 minutes", "Read 20 pages", "No phone after 10pm"]),
      h3("Notes"),
      p(),
    ],
  },
  // ---- Work
  {
    key: "meeting-notes",
    name: "Meeting Notes",
    description: "Agenda, decisions and follow-ups that turn into tasks.",
    icon: "users",
    blocks: () => [callout("note", "**When:** · **Who:**"), h2("Agenda"), n(), h2("Decisions"), b(), h2("Follow-ups"), todo()],
  },
  {
    key: "one-on-one",
    name: "1:1",
    description: "A running page for one-on-ones: check-in, topics, feedback and actions.",
    icon: "messages-square",
    blocks: () => [
      callout("note", "**With:** · **Date:**"),
      h2("Check-in"),
      p("How are things, really?"),
      h2("Their topics"),
      b(),
      h2("My topics"),
      b(),
      h2("Feedback"),
      p(),
      h2("Action items"),
      todo(),
    ],
  },
  {
    key: "standup",
    name: "Daily Standup",
    description: "Yesterday, today and blockers — short enough to fill in two minutes.",
    icon: "timer",
    blocks: () => [h3("Yesterday"), b(), h3("Today"), todo(), h3("Blockers"), callout("warning", "Nothing blocking right now.")],
  },
  {
    key: "project-brief",
    name: "Project Brief",
    description: "Goal, scope, milestones and risks on one page.",
    icon: "compass",
    blocks: () => [
      callout("info", "**Goal:** "),
      h2("Why now"),
      p(),
      h2("Scope"),
      b(),
      h2("Milestones"),
      table(["Milestone", "Owner", "Target"]),
      h2("Risks"),
      b(),
    ],
  },
  {
    key: "product-spec",
    name: "Product Spec",
    description: "Problem, users, requirements and open questions for a feature.",
    icon: "clipboard-list",
    blocks: () => [
      callout("info", "**Status:** Draft · **Owner:** · **Last updated:**"),
      h2("Problem"),
      p("What's hard for people today, and how do we know?"),
      h2("Who it's for"),
      b(),
      h2("Requirements"),
      table(["Requirement", "Priority", "Notes"], ["", "", ""]),
      h2("Out of scope"),
      b(),
      h2("Success looks like"),
      b(),
      h2("Open questions"),
      todo(),
    ],
  },
  {
    key: "decision-record",
    name: "Decision Record",
    description: "Context, options and the call you made — so future you knows why.",
    icon: "scale",
    blocks: () => [
      callout("note", "**Decided on:** · **Decided by:** · **Status:** Proposed"),
      h2("Context"),
      p(),
      h2("Options considered"),
      toggle("Option A", [b("Pros:"), b("Cons:")]),
      toggle("Option B", [b("Pros:"), b("Cons:")]),
      h2("Decision"),
      p(),
      h2("Consequences"),
      b(),
    ],
  },
  {
    key: "retrospective",
    name: "Retrospective",
    description: "What went well, what didn't, and what the team will try next.",
    icon: "history",
    blocks: () => [
      callout("note", "**Sprint / project:** · **Date:**"),
      h2("What went well"),
      b(),
      h2("What didn't"),
      b(),
      h2("What we learned"),
      b(),
      h2("We'll try"),
      todo(),
    ],
  },
  {
    key: "okrs",
    name: "Goals & OKRs",
    description: "Objectives with measurable key results and a place to track progress.",
    icon: "target",
    blocks: () => [
      callout("info", "**Period:** · **Owner:**"),
      h2("Objective 1"),
      table(["Key result", "Start", "Target", "Now"], ["", ""]),
      h2("Objective 2"),
      table(["Key result", "Start", "Target", "Now"], ["", ""]),
      h2("Notes and check-ins"),
      p(),
    ],
  },
  {
    key: "bug-report",
    name: "Bug Report",
    description: "Steps to reproduce, expected and actual behaviour, and environment.",
    icon: "bug",
    blocks: () => [
      callout("danger", "**Severity:** · **Found in:** · **Reported by:**"),
      h2("Summary"),
      p(),
      h2("Steps to reproduce"),
      n(),
      n(),
      n(),
      h2("Expected"),
      p(),
      h2("Actual"),
      p(),
      h2("Environment"),
      b("Device / OS:"),
      b("Browser / app version:"),
      h2("Fix"),
      todo(),
    ],
  },
  {
    key: "client-brief",
    name: "Client Brief",
    description: "Everything about a client engagement: goals, contacts, deliverables and dates.",
    icon: "briefcase",
    blocks: () => [
      callout("note", "**Client:** · **Main contact:** · **Budget:**"),
      h2("What they want"),
      p(),
      h2("Deliverables"),
      table(["Deliverable", "Due", "Status"]),
      h2("Contacts"),
      b(),
      h2("Next steps"),
      todo(),
    ],
  },
  {
    key: "interview-notes",
    name: "Interview Notes",
    description: "Questions, answers and a clear recommendation for a candidate.",
    icon: "user-round-search",
    blocks: () => [
      callout("note", "**Candidate:** · **Role:** · **Interviewer:**"),
      h2("Questions"),
      toggle("Tell me about a project you're proud of.", [p()]),
      toggle("How do you handle disagreement?", [p()]),
      toggle("What would you do in your first 90 days?", [p()]),
      h2("Strengths"),
      b(),
      h2("Concerns"),
      b(),
      h2("Recommendation"),
      callout("info", "Hire · No hire — and why."),
    ],
  },
  // ---- Thinking and learning
  {
    key: "brainstorm",
    name: "Brainstorm",
    description: "Get every idea down first, then cluster and pick the promising ones.",
    icon: "lightbulb",
    blocks: () => [
      callout("note", "**Question we're answering:** "),
      h2("Every idea (no judging yet)"),
      b(),
      b(),
      b(),
      h2("Themes"),
      p(),
      h2("Worth exploring"),
      todo(),
    ],
  },
  {
    key: "reading-notes",
    name: "Reading Notes",
    description: "Quotes, ideas and questions from something you are reading.",
    icon: "book-open",
    blocks: () => [callout("note", "**Author:** · **Started:**"), h2("Big ideas"), b(), h2("Quotes"), quote(), h2("Questions"), b()],
  },
  {
    key: "class-notes",
    name: "Class Notes",
    description: "Cornell-style notes: key points, details, summary and things to review.",
    icon: "graduation-cap",
    blocks: () => [
      callout("note", "**Course:** · **Lecture:** · **Date:**"),
      h2("Key points"),
      b(),
      h2("Details"),
      p(),
      h2("Summary"),
      p("In two or three sentences…"),
      h2("To review"),
      todo(),
    ],
  },
  {
    key: "research-notes",
    name: "Research Notes",
    description: "A question, sources, findings and what they add up to.",
    icon: "flask-conical",
    blocks: () => [
      callout("info", "**Research question:** "),
      h2("Sources"),
      table(["Source", "Type", "Takeaway"]),
      h2("Findings"),
      b(),
      h2("What it means"),
      p(),
      h2("Next questions"),
      b(),
    ],
  },
  {
    key: "writing-draft",
    name: "Writing Draft",
    description: "Outline, draft and a pre-publish checklist for an article or post.",
    icon: "pen-line",
    blocks: () => [
      callout("note", "**Working title:** · **Audience:** · **Due:**"),
      h2("The one idea"),
      p(),
      h2("Outline"),
      n("Hook"),
      n("Main point"),
      n("Wrap-up"),
      h2("Draft"),
      p(),
      divider(),
      h3("Before publishing"),
      todo("Read it out loud"),
      todo("Check links and names"),
      todo("Write a headline and summary"),
    ],
  },
  // ---- Life
  {
    key: "travel-plan",
    name: "Travel Plan",
    description: "Itinerary, bookings and a packing list for a trip.",
    icon: "plane",
    blocks: () => [
      callout("note", "**Where:** · **When:** · **Who:**"),
      h2("Itinerary"),
      table(["Day", "Plan", "Where to stay"], ["Day 1", "Day 2", "Day 3"]),
      h2("Bookings"),
      b("Travel:"),
      b("Stay:"),
      h2("Packing"),
      todo("Passport / ID"),
      todo("Chargers"),
      todo(),
      h2("Ideas"),
      b(),
    ],
  },
  {
    key: "recipe",
    name: "Recipe",
    description: "Ingredients, steps and notes for a dish you want to make again.",
    icon: "chef-hat",
    blocks: () => [
      callout("note", "**Serves:** · **Prep:** · **Cook:**"),
      h2("Ingredients"),
      todo(),
      todo(),
      todo(),
      h2("Method"),
      n(),
      n(),
      n(),
      h2("Notes"),
      p("What to change next time."),
    ],
  },
  {
    key: "workout-log",
    name: "Workout Log",
    description: "Exercises, sets and how it felt — track progress over time.",
    icon: "dumbbell",
    blocks: () => [
      callout("note", "**Date:** · **Focus:**"),
      table(["Exercise", "Sets × reps", "Weight", "Notes"], ["", "", ""]),
      h3("How it felt"),
      p(),
    ],
  },
  {
    key: "budget",
    name: "Monthly Budget",
    description: "Income, planned and actual spending, and savings for the month.",
    icon: "wallet",
    blocks: () => [
      callout("note", "**Month:** · **Income:**"),
      h2("Spending"),
      table(["Category", "Planned", "Actual"], ["Home", "Food", "Transport", "Fun", "Other"]),
      h2("Savings"),
      table(["Goal", "Saved", "Target"]),
      h2("Notes"),
      p(),
    ],
  },
  {
    key: "event-plan",
    name: "Event Plan",
    description: "Guests, timeline, budget and to-dos for a party or event.",
    icon: "party-popper",
    blocks: () => [
      callout("note", "**Event:** · **Date:** · **Place:**"),
      h2("Guests"),
      b(),
      h2("Timeline"),
      table(["Time", "What"], ["", ""]),
      h2("To do"),
      todo("Send invitations"),
      todo("Book the venue"),
      todo(),
      h2("Budget"),
      table(["Item", "Cost"]),
    ],
  },
];

export function builtInTemplateBlocks(key: string): WireBlock[] | null {
  const t = BUILT_IN_TEMPLATES.find((x) => x.key === key);
  return t ? specsToWireBlocks(t.blocks()) : null;
}
