#!/usr/bin/env node
// One-time local setup: generates the development-only token signing key, configures the local
// Convex deployment and writes apps/web/.env.local. Safe to re-run (keeps an existing key).
//
// The dev issuer lets you exercise every workflow locally without an Auth0 tenant. It is disabled
// unless FOLEVI_DEV_AUTH=1 on the web app and FOLEVI_DEV_AUTH_JWKS on Convex — never set either in production.
import { generateKeyPairSync, createPublicKey, randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const webEnvPath = resolve(root, "apps/web/.env.local");
const rootEnv = existsSync(resolve(root, ".env.local")) ? readFileSync(resolve(root, ".env.local"), "utf8") : "";
const convexUrl = /CONVEX_URL=(\S+)/.exec(rootEnv)?.[1] ?? "http://127.0.0.1:3210";
const convexSite = /CONVEX_SITE_URL=(\S+)/.exec(rootEnv)?.[1] ?? "http://127.0.0.1:3211";

function parseEnv(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

const existing = existsSync(webEnvPath) ? parseEnv(readFileSync(webEnvPath, "utf8")) : {};
let privatePem = existing.FOLEVI_DEV_AUTH_PRIVATE_KEY ? Buffer.from(existing.FOLEVI_DEV_AUTH_PRIVATE_KEY, "base64").toString("utf8") : null;
if (!privatePem) {
  const { privateKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  privatePem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();
}
const jwk = createPublicKey(privatePem).export({ format: "jwk" });
const kid = "folevi-dev-1";
const jwks = JSON.stringify({ keys: [{ ...jwk, kid, alg: "RS256", use: "sig" }] });
const issuer = "http://localhost:3000/dev-auth";

const env = {
  ...existing,
  NEXT_PUBLIC_CONVEX_URL: convexUrl,
  NEXT_PUBLIC_CONVEX_SITE_URL: convexSite,
  NEXT_PUBLIC_APP_URL: existing.NEXT_PUBLIC_APP_URL ?? "http://app.localhost:3000",
  NEXT_PUBLIC_MARKETING_URL: existing.NEXT_PUBLIC_MARKETING_URL ?? "http://localhost:3000",
  FOLEVI_DEV_AUTH: "1",
  FOLEVI_DEV_AUTH_ISSUER: issuer,
  FOLEVI_DEV_AUTH_KID: kid,
  FOLEVI_DEV_AUTH_PRIVATE_KEY: Buffer.from(privatePem).toString("base64"),
  FOLEVI_SERVER_SECRET: existing.FOLEVI_SERVER_SECRET ?? randomBytes(32).toString("hex"),
  FOLEVI_SESSION_SECRET: existing.FOLEVI_SESSION_SECRET ?? randomBytes(32).toString("hex"),
};
writeFileSync(
  webEnvPath,
  `# Local development only — generated by scripts/setup-local.mjs. Never commit.\n${Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")}\n`,
);
console.log(`wrote ${webEnvPath}`);

const convexEnv = {
  FOLEVI_ENV: "development",
  FOLEVI_DEV_AUTH_JWKS: jwks,
  FOLEVI_DEV_AUTH_ISSUER: issuer,
  FOLEVI_APP_URL: env.NEXT_PUBLIC_APP_URL,
  FOLEVI_SERVER_SECRET: env.FOLEVI_SERVER_SECRET,
  FOLEVI_HASH_SALT: randomBytes(16).toString("hex"),
  // Referenced by convex/auth.config.ts; "none" keeps Auth0 disabled until a tenant is configured.
  AUTH0_DOMAIN: "none",
  AUTH0_WEB_CLIENT_ID: "none",
  AUTH0_MAC_CLIENT_ID: "none",
};
for (const [key, value] of Object.entries(convexEnv)) {
  if (key === "FOLEVI_HASH_SALT" || key.startsWith("AUTH0_")) {
    try {
      const current = execFileSync("npx", ["convex", "env", "get", key], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
      if (current) continue;
    } catch {
      /* not set yet */
    }
  }
  execFileSync("npx", ["convex", "env", "set", key, value], { cwd: root, stdio: "inherit" });
}
console.log("Local Convex deployment configured for development sign-in.");
