#!/usr/bin/env node
// One-time local setup: configures the local Convex deployment for Folevi's built-in accounts and
// writes apps/web/.env.local. Safe to re-run (keeps existing secrets).
//
// Locally, identity emails (verification, password reset) are captured in the development mailbox at
// http://app.localhost:3000/dev/mailbox instead of being sent. That mailbox never works in production.
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const webEnvPath = resolve(root, "apps/web/.env.local");
const rootEnv = existsSync(resolve(root, ".env.local")) ? readFileSync(resolve(root, ".env.local"), "utf8") : "";
const convexUrl = /CONVEX_URL=(\S+)/.exec(rootEnv)?.[1] ?? "http://127.0.0.1:3210";
const convexSite = /CONVEX_SITE_URL=(\S+)/.exec(rootEnv)?.[1] ?? "http://127.0.0.1:3211";

function parseEnv(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

const RETIRED = ["FOLEVI_DEV_AUTH", "FOLEVI_DEV_AUTH_ISSUER", "FOLEVI_DEV_AUTH_KID", "FOLEVI_DEV_AUTH_PRIVATE_KEY", "FOLEVI_SESSION_SECRET", "FOLEVI_ALLOW_DEV_AUTH_BUILD"];
const existing = existsSync(webEnvPath) ? parseEnv(readFileSync(webEnvPath, "utf8")) : {};
for (const k of RETIRED) delete existing[k];

const env = {
  ...existing,
  NEXT_PUBLIC_CONVEX_URL: convexUrl,
  NEXT_PUBLIC_CONVEX_SITE_URL: convexSite,
  NEXT_PUBLIC_APP_URL: existing.NEXT_PUBLIC_APP_URL ?? "http://app.localhost:3000",
  NEXT_PUBLIC_MARKETING_URL: existing.NEXT_PUBLIC_MARKETING_URL ?? "http://localhost:3000",
  FOLEVI_SERVER_SECRET: existing.FOLEVI_SERVER_SECRET ?? randomBytes(32).toString("hex"),
  FOLEVI_DEV_MAILBOX_SECRET: existing.FOLEVI_DEV_MAILBOX_SECRET ?? randomBytes(24).toString("hex"),
};
writeFileSync(
  webEnvPath,
  `# Local development only — generated by scripts/setup-local.mjs. Never commit.\n${Object.entries(env)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n")}\n`,
);
console.log(`wrote ${webEnvPath}`);

function convexGet(key) {
  try {
    return execFileSync("npx", ["convex", "env", "get", key], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

const convexEnv = {
  FOLEVI_ENV: "development",
  FOLEVI_APP_URL: env.NEXT_PUBLIC_APP_URL,
  SITE_URL: env.NEXT_PUBLIC_APP_URL,
  FOLEVI_SERVER_SECRET: env.FOLEVI_SERVER_SECRET,
  FOLEVI_DEV_MAILBOX_SECRET: env.FOLEVI_DEV_MAILBOX_SECRET,
};
const KEEP_IF_SET = { FOLEVI_HASH_SALT: () => randomBytes(16).toString("hex"), BETTER_AUTH_SECRET: () => randomBytes(32).toString("base64") };
for (const [key, make] of Object.entries(KEEP_IF_SET)) if (!convexGet(key)) convexEnv[key] = make();
for (const [key, value] of Object.entries(convexEnv)) execFileSync("npx", ["convex", "env", "set", key, value], { cwd: root, stdio: "inherit" });
for (const key of ["AUTH0_DOMAIN", "AUTH0_WEB_CLIENT_ID", "AUTH0_MAC_CLIENT_ID", "FOLEVI_DEV_AUTH_JWKS", "FOLEVI_DEV_AUTH_ISSUER"]) {
  if (convexGet(key)) execFileSync("npx", ["convex", "env", "remove", key], { cwd: root, stdio: "ignore" });
}
console.log("Local Convex deployment configured. Create an account at http://app.localhost:3000/signup — confirmation links appear at /dev/mailbox.");
